# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-slim
WORKDIR /app
# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc libssl-dev libffi-dev \
    && pip install --no-cache-dir pip setuptools wheel
# Copy and install dependencies
COPY pyproject.toml uv.lock ./
RUN pip install --no-cache-dir . \
    && apt-get remove -y gcc libssl-dev libffi-dev \
    && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*
# Copy application code
COPY . .
# Create start script to use stdio transport
RUN printf "from main import mcp\nif __name__=='__main__':\n    mcp.run()\n" > start.py
# Expose default MCP standard isn't HTTP; stdio uses stdin/stdout so no port
EXPOSE 10000
# Default command
CMD ["python","start.py"]
